[loadConfiguration]
command:/usr/local/opnsense/scripts/opncell/reconfigure.py
type:script_output
parameters:%s
message: Loading daemon configuration

[saveUsers]
command: /usr/local/opnsense/scripts/opncell/saveUsers.py
type:script_output
parameters:%s
message:Saving users to HSS database.

[getUser]
command: /usr/local/opnsense/scripts/opncell/getUser.py
type:script_output
parameters:%s
message:Get User from db.

[showUsers]
command:/usr/local/opnsense/scripts/opncell/showUsers.py
type:script_output
parameters:%s
message: getting all Users

[showHnet]
command:/usr/local/opnsense/scripts/opncell/generate_hnet.py
type:script_output
parameters:%s
message: Configuring Hnet

[showUsersFiltered]
command:/usr/local/opnsense/scripts/opncell/showUsersFiltered.py
parameters: --sort_by=%s
type:script_output
message: getting all Users

[processNames]
command:/usr/local/opnsense/scripts/opncell/processNames.py
parameters:%s
type:script_output
message: Process names

[deleteUser]
command:/usr/local/opnsense/scripts/opncell/deleteUser.py
type:script_output
parameters:%s
message: Deleting User

[updateUser]
command:/usr/local/opnsense/scripts/opncell/updateUser.py
type:script_output
parameters:%s
message: Updating User

[startMongo]
command:/usr/local/opnsense/scripts/opncell/startMongo.sh
type:script_output
message:Starting mongoDB

[restartMongo]
command:/usr/local/opnsense/scripts/opncell/startMongo.sh
type:script_output
message:Restarting mongoDB

[stopMongo]
command:/usr/local/opnsense/scripts/opncell/stopMongo.sh
type:script
message:Stopping mongoDB

[saveTuneables]
command:/usr/local/opnsense/scripts/opncell/saveTuneables.py
type:script_output
parameters:%s
message: Loading daemon configuration

[editServerConf]
command:/usr/local/opnsense/scripts/opncell/editSingleService.py
type:script_output
parameters:%s
message: Editing Conf file
