version: "3.6"
services:
  service_php:
    build:
      context: ./docker/php
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
      - ./docker/php/mods/psr.ini:/etc/php/7.4/fpm/conf.d/20-psr.ini
      - ./docker/php/mods/phalcon.ini:/etc/php/7.4/fpm/conf.d/50-phalcon.ini
      - ./docker/php/mods/psr.ini:/etc/php/7.4/cli/conf.d/20-psr.ini
      - ./docker/php/mods/phalcon.ini:/etc/php/7.4/cli/conf.d/50-phalcon.ini
    depends_on:
      - service_mysql
      - service_postgres

  service_nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./docker/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
    depends_on:
      - service_php

  service_mysql:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=devtools
      - MYSQL_USER=devtools
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_mysql_data:/var/lib/mysql/
      - ./docker/mysql/config:/etc/mysql/conf.d/

  service_postgres:
    image: postgis/postgis:13-master
    restart: always
    environment:
      - POSTGRES_USER=devtools
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devtools
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d devtools -U devtools
      timeout: 5s

volumes:
  db_mysql_data:
  db_postgres_data:
