PLUGIN_NAME=		cellular
PLUGIN_VERSION=		24.8_1
PLUGIN_COMMENT=		Off the self way of deploying private networks application

PLUGIN_DEPENDS=	        libmicrohttpd \
                        cmake \
                        ninja \
                        bison \
                        pkgconf \
                        git \
                        gnutls \
                        libgcrypt \
                        libidn \
                        libyaml \
                        talloc \
                        gmake \
                        gsed \
                        mongodb-tools \
                        gcc13 \
                        py311-setuptools \
                        python${PLUGIN_PYTHON} \
                        meson \
                        mongo-c-driver \
                        nghttp2 \
                        mongodb44 \
                        open5gs \

PLUGIN_MAINTAINER=	support@ds.co.ug

.include "../../Mk/plugins.mk"