PLUGIN_NAME=		cellular
PLUGIN_VERSION=		24.5.1_2
PLUGIN_COMMENT=		Off-the-shelf way of deploying a secure cellular core network
PLUGIN_DEPENDS=	        libmicrohttpd \
                        cmake \
                        ninja \
                        bison \
                        pkgconf \
                        git \
                        gnutls \
                        libgcrypt \
                        libidn \
                        libyaml \
                        talloc \
                        gmake \
                        mongodb-tools \
                        gsed \
                        gcc \
                        py${PLUGIN_PYTHON}-setuptools \
                        python${PLUGIN_PYTHON} \
                        meson \
                        mongo-c-driver \
                        nghttp2 \
                        mongodb44 \
                        open5gs \

PLUGIN_MAINTAINER=	support@ds.co.ug

.include "../../Mk/plugins.mk"
