PLUGIN_NAME=		cellular
PLUGIN_VERSION=		25.1_2
PLUGIN_COMMENT=		Off the shelf way of deploying private networks application
PLUGIN_DEPENDS=	        open5gs \

PLUGIN_MAINTAINER=	support@ds.co.ug

.include "../../Mk/plugins.mk"