#!/bin/sh
#
# PROVIDE: epcausfd

# KEYWORD: shutdown

. /etc/rc.subr

name=epcausfd
service_name=ausfd
desc="AUS daemon"
rcvar=${name}_enable
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcausfd_enable:="NO"}"

epcausfd_start(){
        echo "Starting open5gs-${service_name} daemon"
       
        mkdir -p /var/run/epc
        pidfile="/var/run/epc/epcausfd.pid"

        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pidfile} ${service_name}; then
                echo "Started"
        else
                echo "Failed to start"
        fi
}

run_rc_command "$1"
