#!/bin/sh
#
# PROVIDE: epchssd
# REQUIRE: mongod
# KEYWORD: shutdown

. /etc/rc.subr

name=epchssd
service_name=hssd
desc="Home Subscriber System Daemon"
rcvar=${name}_enable
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epchssd_enable:="NO"}"
#: "${epc_config="/usr/local/etc/epc/epc.conf"}"

required_files="${epc_config}"


epchssd_start(){
    	echo "Starting open5gs-${service_name} daemon"
        sleep 4        
#	mkdir -p /var/run/epc
	pfile="/var/run/epc/epchssd.pid"
	cd /tmp || exit 1

	if /usr/local/etc/rc.d/startmmed.sh ${command} ${pfile}; then
    		echo "Started"
	else
    		echo "Failed to start"
	fi
}

run_rc_command "$1"


