#!/bin/sh
#
# PROVIDE: epcmmed
# REQUIRE: mongod
# KEYWORD: shutdown

. /etc/rc.subr

name=epcmmed
service_name=mmed
desc="Mobility Management Entity Daemon"
rcvar=${name}_enable
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcmmed_enable:="NO"}"
: "${epcmmed_config="/usr/local/etc/epc/epcmmed.conf"}"

required_files="${epc_config}"


epcmmed_start(){
    echo "Starting open5gs-${service_name} daemon"

mkdir -p /var/run/epc
pfile="/var/run/epc/epcmmed.pid"
cd /tmp || exit 1
if /usr/local/etc/rc.d/startmmed.sh ${command} ${pfile}; then
    echo "Started"
else
    echo "Failed to start"
fi
} 



run_rc_command "$1"
