#!/bin/sh
#
# PROVIDE: epcnrfd
#
# KEYWORD: shutdown

. /etc/rc.subr

name=epcnrfd
service_name=nrfd
desc="Network Routing Function Daemon"
rcvar=${name}_enable
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcnrfd_enable:="NO"}"

epcnrfd_start(){
        echo "Starting open5gs-${service_name} daemon"
        
        mkdir  /var/run/epc
        pidfile="/var/run/epc/epcnrfd.pid"

        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pidfile} ${service_name}; then
                echo "Started"
        else
                echo "Failed to start"
        fi
}

run_rc_command "$1"
