#!/bin/sh
#
# PROVIDE: epcpcfd

# KEYWORD: shutdown

. /etc/rc.subr

name=epcpcfd
service_name=pcfd
desc="AMF daemon"
rcvar=${name}_enable
config_file="/usr/local/etc/open5gs/pcf.yaml"
log_file="/var/log/opncell/pcf.log"
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcpcfd_enable:="NO"}"

epcpcfd_start(){
        echo "Starting open5gs-${service_name} daemon"
        
        mkdir -p /var/run/epc
        pidfile="/var/run/epc/epcpcfd.pid"

        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pidfile} ${service_name} ${config_file} ${log_file}; then
                echo "Started"
        else
                echo "Failed to start"
        fi
}

run_rc_command "$1"

