#!/bin/sh
#
# PROVIDE: epcsmfd

# KEYWORD: shutdown

. /etc/rc.subr

name=epcsmfd
service_name=smfd
desc="SMF daemon"
rcvar=${name}_enable
config_file="/usr/local/etc/open5gs/smf.yaml"
log_file="/var/log/opncell/smf.log"
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcsmfd_enable:="NO"}"

epcsmfd_start(){
        echo "Starting open5gs-${service_name} daemon"
        mkdir -p /var/run/epc
        pidfile="/var/run/epc/epcsmfd.pid"

        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pidfile} ${service_name} ${config_file} ${log_file}; then
                echo "Started"
        else
                echo "Failed to start"
        fi
}

run_rc_command "$1"
