#!/bin/sh
#
# PROVIDE: epcsgwcd
# KEYWORD: shutdown

. /etc/rc.subr

name=epcsgwcd
service_name=sgwcd
desc="SGWC daemon"
rcvar=${name}_enable
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcsgwcd_enable:="NO"}"
#: "${epc_config="/usr/local/etc/epc/epc.conf"}"

#required_files="${epc_config}"


epcsgwcd_start(){
        echo "Starting open5gs-${service_name} daemon"
        #chmod +x /tmp/startmmed.sh
        mkdir -p /var/run/epc
        pfile="/var/run/epc/epcsgwcd.pid"
        cd /tmp || exit 1

        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pfile}; then
                echo "Started"
        else
                echo "Failed to start"
        fi
}

run_rc_command "$1"
