#!/bin/sh
#
# PROVIDE: epcscpd
# KEYWORD: shutdown

. /etc/rc.subr

name=epcscpd
service_name=scpd
desc="Service Communication Protocol Daemon"
rcvar=${name}_enable
config_file="/usr/local/etc/open5gs/scp.yaml"
log_file="/var/log/opncell/scp.log"
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcscpd_enable:="NO"}"
#: "${epc_config="/usr/local/etc/epc/epc.conf"}"

#required_files="${epc_config}"


epcscpd_start(){
        echo "Starting open5gs-${service_name} daemon"

        mkdir -p /var/run/epc
        pidfile="/var/run/epc/epcscpd.pid"

        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pidfile} ${service_name} ${config_file} ${log_file}; then
                echo "Started"
        else
                echo "Failed to start"
        fi
}

run_rc_command "$1"
