#!/bin/sh
#
# PROVIDE: epcupfd
# REQUIRE: mongod
# KEYWORD: shutdown

. /etc/rc.subr

name=epcupfd
service_name=upfd
desc="upf daemon"
rcvar=${name}_enable
config_file="/usr/local/etc/open5gs/upf.yaml"
log_file="/var/log/opncell/upf.log"
command="/usr/ports/open5gs/install/bin/open5gs-${service_name}"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
command_args="-D > /dev/null 2>&1"

load_rc_config ${name}
: "${epcupfd_enable:="NO"}"

epcupfd_start(){
        echo "Starting open5gs-${service_name} daemon"
        mkdir -p /var/run/epc
        pidfile="/var/run/epc/epcupfd.pid"

        if ifconfig | grep -q epc0; then
           ifconfig epc0 name tun0 > /dev/null 2>&1
        fi
        
        if /usr/local/etc/rc.d/startmmed.sh ${command} ${pidfile} ${service_name} ${config_file} ${log_file}; then
                echo "Started"
                sleep 10   #Wait for daemon to initialize before renaming tun0 
        else
                echo "Failed to start"
        fi
        if ifconfig | grep -q tun0; then
           ifconfig tun0 name epc0 > /dev/null 2>&1
        fi
}

epcupfd_stop(){
        echo "Starting open5gs-${service_name} daemon"
            pid=$(pgrep open5gs-upfd)
    	    kill -9  ${pid}
            rm /var/run/epc/epcupfd.pid
             if ifconfig | grep -q epc0; then
               ifconfig epc0 name tun0 > /dev/null 2>&1
             fi
          
}

run_rc_command "$1"
