#!/bin/sh

# PROVIDE: mongod
# REQUIRE: NETWORK ldconfig
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# mongod_enable (bool):  Set to "NO" by default.
#                        Set it to "YES" to enable mongod.
# mongod_dbpath (str):   Default to "/var/db/mongodb"
#                        Base database directory.
# mongod_flags (str):    Custom additional arguments to be passed to mongod.
#                        Default to "--logpath ${mongod_dbpath}/mongod.log --logappend".
# mongod_config (str):	 Default to "/usr/local/etc/mongodb.conf"
#                        Path to config file
#

. /etc/rc.subr

name="mongod"
rcvar=mongod_enable

mkdir -p /var/run/epc/
mkdir -p /var/log/opncell/

load_rc_config $name

: ${mongod_enable="YES"}
: ${mongod_dbpath="/usr/local/bin/data/db"}
#: ${mongod_flags="--logpath ${mongod_dbpath}/mongod.log --logappend --setParameter=disabledSecureAllocatorDomains=\*"}
: ${mongod_user="root"}
: ${mongod_group="wheel"}
: ${mongod_config="/usr/local/etc/mongodb.conf"}

pidfile="${mongod_dbpath}/mongod.lock"
command=/usr/local/bin/${name}
command_args="--config $mongod_config --dbpath $mongod_dbpath --fork --pidfilepath /var/run/epc/epcmongod.pid --logpath /var/log/opncell/mongod.log --logappend  >/dev/null 2>/dev/null"
start_precmd="${name}_prestart"

mongod_create_dbpath()
{
        mongo_binary_path=$(which mongod)
        directory_path=$(dirname "$mongo_binary_path")
        cd "$directory_path" || exit 1
        mkdir -p ./data/db >/dev/null 2>/dev/null
        [ $? -eq 0 ] && chown -R ${mongod_user}:${mongod_group} ${mongod_dbpath}

}

mongod_prestart()
{
        if [ ! -d ${mongod_dbpath} ]; then
                mongod_create_dbpath || return 1
        fi
        return 0
}

run_rc_command "$1"
